### ISSUE TITLE
train_meta64x64.json

### ISSUE THREAD

**Issue by Herb996** [shgaurav1/DVG#3]
I have solved the previous problem, but now I have a dataset problem. How to obtain the JSON files? Can you provide six JSON files?
thanks.

**Comment by Herb996** [comment]
maybe 12

**Comment by zhanghaobucunzai** [comment]
请问该文件获取到了吗，能否共享一份？

**Comment by shgaurav1** [comment]
@Herb996 and @zhanghaobucunzai, you can find the JSON files [here](https://drive.google.com/file/d/1si3aUYWv1iqDIvA6gHQbxKII4lui7vVP/view?usp=sharing).
